apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-edge-linedataserver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tapatel/manuela-gitops.git
    targetRevision: HEAD
    path: deployment/gcp-edge-linedatacenter
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status