apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.1-8
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-8
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-9
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-9
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-10
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-10
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-11
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-11
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-13
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-13
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-14
    from:
      kind: DockerImage
      name: quay.io/tapatel/iot-software-sensor:0.3.1-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-15
    from:
      kind: DockerImage
      name: quay.io/tapatel/iot-software-sensor:0.3.1-15
    importPolicy: {}
    referencePolicy:
      type: Local
